name: SambaNova SonarQube Quality Analysis

on:
  # Jalankan pada pull request
  pull_request:
    branches: [ main, master ]
  # Memungkinkan pemicu manual dari tab Actions
  workflow_dispatch:

jobs:
  changes:
    name: Check changed files
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      python: ${{ steps.filter.outputs.python }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            python:
              - '**/*.py'
  
  sonarqube-analysis:
    name: SonarQube Analysis
    needs: changes
    # Jalankan jika ada perubahan file Python atau ini adalah pemicu manual
    if: ${{ needs.changes.outputs.python == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Dibutuhkan untuk mendapatkan semua commit history untuk SonarQube
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          # Jika ada file requirements.txt
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # Jika menggunakan pipenv
          if [ -f Pipfile ]; then
            pip install pipenv
            pipenv install --dev
          fi
      
      - name: Run tests with coverage
        run: |
          # Pilih salah satu command sesuai dengan struktur proyek
          if [ -f Pipfile ]; then
            # Gunakan pipenv jika ada
            pipenv run pytest --cov=. --cov-report=xml:coverage.xml
          else
            # Atau langsung menggunakan pytest
            pytest --cov=. --cov-report=xml:coverage.xml
          fi
      
      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}